### ISSUE TITLE
EMA Delay

### ISSUE THREAD

**Issue by DanielaGarza** [MD2Korg/mCerebrum-NotificationManager#2]
Date: 4/5/2016
Time: 4:00 PM
EMA was prompted by phone and user delayed EMA. When user wanted to go back in to the phone and continue EMA before the delay time had expired, the user had to go through the phone notification system (as in the bar you can swipe down on android phones to see notifications) to continue EMA. Participants should be able to initiate delayed EMA through the mCerebrum app as well.

**Comment by twhnat** [comment]
Per our discussion, we will wait for more field testing to determine if this is an issue.  The system will automatically remind a participant after 10 minutes.
